name: generate monkeytype readme svg

on:
  push:
    branches:
      - monkeytype-readme
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  download-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Download SVG
        run: |
          mkdir monkeytype-readme-svg
          curl -o monkeytype-readme-svg/monkeytype-readme.svg https://monkeytype-readme.com/generate-svg/DE__BLANK__/onedark
          curl -o monkeytype-readme-svg/monkeytype-readme-lb.svg https://monkeytype-readme.com/generate-svg/DE__BLANK__/onedark?lb=true
          curl -o monkeytype-readme-svg/monkeytype-readme-pb.svg https://monkeytype-readme.com/generate-svg/DE__BLANK__/onedark?pb=true
          curl -o monkeytype-readme-svg/monkeytype-readme-lb-pb.svg https://monkeytype-readme.com/generate-svg/DE__BLANK__/onedark?lbpb=true

      - name: push monkeytype-readme.svg to the monkeytype-readme branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: monkeytype-readme
          build_dir: monkeytype-readme-svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
